### ISSUE TITLE
Fix your security issue

### ISSUE THREAD

**Issue by ahamilton55** [CSUN-SeniorDesign/zephyr-blog#1]
GitHub has noticed a security issue in your current set of JavaScript packages. Please fix this issue ASAP.

![image](https://user-images.githubusercontent.com/936174/45008729-18854d80-afb9-11e8-8388-6eee20ed06a8.png)

**Comment by PRDarkness** [comment]
Fixed by running the command: npm audit fix

**Comment by ahamilton55** [comment]
Issue is still there...

![image](https://user-images.githubusercontent.com/936174/45257225-8b931900-b357-11e8-840a-c92be6fd0f03.png)

**Comment by ahamilton55** [comment]
Still not fixed.

**Comment by Neelpatel2295** [comment]
Tonny updated  hoek to fix the issue.

**Comment by hirahokad** [comment]
Tonny updated Hugo Lamp themes Packages.

**Comment by ahamilton55** [comment]
Cool. Vulnerability is gone.
