### ISSUE TITLE
Setup AWS Virtual Private Cloud ( VPC )

### ISSUE THREAD

**Issue by hirahokad** [CSUN-SeniorDesign/zephyr-blog#3]
- [x] Create 3 Public Subnets in 3 different availability zones with at least 1024 available IP addresses per subnet.

- [x] 3 private subnets in 3 different availability zones (AZ) with at least 4096 available IP
addresses per subnet.

- [x] 1 route table for the public subnets

- [x] 1 route table for the private subnets

- [x] 1 Internet Gateway (IG) attached to the default route of the public subnet routing table

**Comment by PRDarkness** [comment]
Done.
