### ISSUE TITLE
Create Documentation and Finish Deliverables

### ISSUE THREAD

**Issue by hirahokad** [CSUN-SeniorDesign/zephyr-blog#9]
- [x] A running website on a service in AWS EC2 that is publicly available over your DNS
address using HTTPS
- [x] Individual blog posts (1 each week by each member, 2 total per person) saved to your
blog repo and publicly available on your site
- [x] Complete documentation of all tasks performed. Documentation must be clear, concise
and complete as to not leave anything out.

You should have the following documents in your infrastructure repository as a set of
markdown files

- [x] README.md for each repo giving basic information

- [x] AWS setup

- [x] AWS services setup (EC2, VPC, Route53, etc)

- [x]  AWS service diagram showing each aspect of the infrastructure

- [x]  How to write a blog post

- [x] How to deploy a new blog post

**Comment by PRDarkness** [comment]
Done by all of us.

**Comment by Neelpatel2295** [comment]
Done and uploaded.
